# Generated by Django 5.1.5 on 2025-01-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testfastprint', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produk',
            name='nama',
            field=models.CharField(max_length=255),
        ),
    ]
